services:
  postgres:
    image: postgres:17-alpine
    pull_policy: missing
    shm_size: 128mb
    ports:
      - "5432:5432"
    volumes:
      - postgres_gobite_data:/var/lib/postgresql/data
    networks:
      - gobite-network
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: gobite
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=user --dbname=gobite"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  redis:
    image: redis:8.2-alpine
    pull_policy: missing
    ports:
      - "6379:6379"
    volumes:
      - redis_gobite_data:/data
    networks:
      - gobite-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  mailhog:
    image: mailhog/mailhog:v1.0.1
    pull_policy: missing
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI
    networks:
      - gobite-network

  nsqlookupd:
    image: nsqio/nsq:v1.3.0
    pull_policy: missing
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
    networks:
      - gobite-network
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 4160"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  nsqd:
    image: nsqio/nsq:v1.3.0
    pull_policy: missing
    command: >
      /nsqd
      --lookupd-tcp-address=nsqlookupd:4160
      --broadcast-address=localhost
      --data-path=/data
    ports:
      - "4150:4150"
      - "4151:4151"
    volumes:
      - nsq_gobite_data:/data
    depends_on:
      nsqlookupd:
        condition: service_healthy
    networks:
      - gobite-network
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 4150"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_gobite_data:
  redis_gobite_data:
  nsq_gobite_data:

networks:
  gobite-network:
    driver: bridge
