// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pkgsql

import (
	"github.com/jackc/pgx/v5/pgtype"
	auth_entity "github.com/shandysiswandi/gobite/internal/auth/entity"
	notif_entity "github.com/shandysiswandi/gobite/internal/notification/entity"
)

type MfaBackupCode struct {
	ID          int64
	MfaFactorID int64
	Code        string
	IsUsed      bool
}

type MfaFactor struct {
	ID           int64
	UserID       int64
	Type         int16
	FriendlyName string
	Secret       []byte
	KeyVersion   int16
	IsVerified   bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Notification struct {
	ID         int64
	UserID     int64
	CategoryID int64
	TriggerKey string
	Data       notif_entity.JSONMap
	Metadata   notif_entity.JSONMap
	ReadAt     pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type NotificationCategory struct {
	ID          int64
	Name        string
	Description string
	IsMandatory bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type NotificationDeliveryLog struct {
	ID               int64
	NotificationID   int64
	Channel          notif_entity.Channel
	Status           notif_entity.DeliveryStatus
	AttemptCount     int32
	NextRetryAt      pgtype.Timestamptz
	ProviderResponse notif_entity.JSONMap
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type NotificationTemplate struct {
	ID         int64
	TriggerKey string
	CategoryID int64
	Channel    notif_entity.Channel
	Subject    string
	Body       string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type NotificationUserDevice struct {
	ID           int64
	UserID       int64
	DeviceToken  string
	Platform     string
	LastActiveAt pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type NotificationUserSetting struct {
	UserID     int64
	CategoryID int64
	Channel    notif_entity.Channel
	IsEnabled  bool
	UpdatedAt  pgtype.Timestamptz
}

type Permission struct {
	ID          int64
	Action      string
	Resource    string
	Description string
}

type Role struct {
	ID          int64
	Name        string
	Description string
}

type RolePermission struct {
	RoleID       int64
	PermissionID int64
}

type User struct {
	ID        int64
	Email     string
	FullName  string
	AvatarUrl string
	Status    auth_entity.UserStatus
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type UserConnection struct {
	ID             int64
	UserID         int64
	Provider       string
	ProviderUserID string
	CreatedAt      pgtype.Timestamptz
}

type UserCredential struct {
	UserID    int64
	Password  string
	UpdatedAt pgtype.Timestamptz
}

type UserPasswordReset struct {
	ID        int64
	UserID    int64
	Token     string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type UserRole struct {
	UserID int64
	RoleID int64
}
