// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pkgsql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MfaBackupCode struct {
	ID          int64
	MfaFactorID int64
	Code        string
	IsUsed      bool
}

type MfaFactor struct {
	ID           int64
	UserID       int64
	Type         int16
	FriendlyName string
	Secret       []byte
	KeyVersion   int16
	IsVerified   bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Permission struct {
	ID          int64
	Action      string
	Resource    string
	Description string
}

type Role struct {
	ID          int64
	Name        string
	Description string
}

type RolePermission struct {
	RoleID       int64
	PermissionID int64
}

type User struct {
	ID        int64
	Email     string
	FullName  string
	AvatarUrl string
	Status    int16
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type UserConnection struct {
	ID             int64
	UserID         int64
	Provider       string
	ProviderUserID string
	CreatedAt      pgtype.Timestamptz
}

type UserCredential struct {
	UserID    int64
	Password  string
	UpdatedAt pgtype.Timestamptz
}

type UserRole struct {
	UserID int64
	RoleID int64
}
