// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pkgsql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MfaBackupCode struct {
	ID          int64
	MfaFactorID int64
	HashedCode  string
	IsUsed      bool
}

type MfaFactor struct {
	ID                   int64
	UserID               int64
	Type                 int16
	FriendlyName         pgtype.Text
	EncryptedSecret      []byte
	EncryptionKeyVersion int16
	IsVerified           bool
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type Permission struct {
	ID          int64
	Action      string
	Resource    string
	Description pgtype.Text
}

type Role struct {
	ID          int64
	Name        string
	Description pgtype.Text
}

type RolePermission struct {
	RoleID       int64
	PermissionID int64
}

type User struct {
	ID        int64
	Email     string
	FullName  string
	AvatarUrl pgtype.Text
	Status    int16
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type UserConnection struct {
	ID             int64
	UserID         int64
	Provider       string
	ProviderUserID string
	CreatedAt      pgtype.Timestamptz
}

type UserCredential struct {
	UserID                int64
	HashedPassword        string
	PasswordLastChangedAt pgtype.Timestamptz
}

type UserRole struct {
	UserID int64
	RoleID int64
}
