// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_auth.sql

package pkgsql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const mfaFactorGetByUserID = `-- name: MfaFactorGetByUserID :many

SELECT id, user_id, type, friendly_name, secret, key_version, is_verified, created_at, updated_at FROM mfa_factors 
WHERE 
    user_id = $1 AND 
    is_verified = $2
`

type MfaFactorGetByUserIDParams struct {
	UserID     int64
	IsVerified bool
}

// ----- ----- ----- ----- -----
// mfa_factors table
// ----- ----- ----- ----- -----
func (q *Queries) MfaFactorGetByUserID(ctx context.Context, arg MfaFactorGetByUserIDParams) ([]MfaFactor, error) {
	rows, err := q.db.Query(ctx, mfaFactorGetByUserID, arg.UserID, arg.IsVerified)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MfaFactor
	for rows.Next() {
		var i MfaFactor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.FriendlyName,
			&i.Secret,
			&i.KeyVersion,
			&i.IsVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userCreate = `-- name: UserCreate :exec
INSERT INTO users (id, email, full_name, avatar_url, status)
VALUES ($1, $2, $3, $4, $5)
`

type UserCreateParams struct {
	ID        int64
	Email     string
	FullName  string
	AvatarUrl string
	Status    int16
}

func (q *Queries) UserCreate(ctx context.Context, arg UserCreateParams) error {
	_, err := q.db.Exec(ctx, userCreate,
		arg.ID,
		arg.Email,
		arg.FullName,
		arg.AvatarUrl,
		arg.Status,
	)
	return err
}

const userCredentialCreate = `-- name: UserCredentialCreate :exec
INSERT INTO user_credentials (user_id, password)
VALUES ($1, $2)
`

type UserCredentialCreateParams struct {
	UserID   int64
	Password string
}

func (q *Queries) UserCredentialCreate(ctx context.Context, arg UserCredentialCreateParams) error {
	_, err := q.db.Exec(ctx, userCredentialCreate, arg.UserID, arg.Password)
	return err
}

const userCredentialGetByUserID = `-- name: UserCredentialGetByUserID :one

SELECT user_id, password, updated_at FROM user_credentials 
WHERE 
    user_id = $1
`

// ----- ----- ----- ----- -----
// user_credentials table
// ----- ----- ----- ----- -----
func (q *Queries) UserCredentialGetByUserID(ctx context.Context, userID int64) (UserCredential, error) {
	row := q.db.QueryRow(ctx, userCredentialGetByUserID, userID)
	var i UserCredential
	err := row.Scan(&i.UserID, &i.Password, &i.UpdatedAt)
	return i, err
}

const userCredentialUpdate = `-- name: UserCredentialUpdate :exec
UPDATE user_credentials 
SET 
    password = $1
WHERE user_id = $2
`

type UserCredentialUpdateParams struct {
	Password string
	UserID   int64
}

func (q *Queries) UserCredentialUpdate(ctx context.Context, arg UserCredentialUpdateParams) error {
	_, err := q.db.Exec(ctx, userCredentialUpdate, arg.Password, arg.UserID)
	return err
}

const userGetByEmail = `-- name: UserGetByEmail :one

SELECT id, email, full_name, avatar_url, status, deleted_at, created_at, updated_at FROM users 
WHERE 
    email = $1 AND 
    deleted_at IS NULL
`

// ----- ----- ----- ----- -----
// users table
// ----- ----- ----- ----- -----
func (q *Queries) UserGetByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, userGetByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.AvatarUrl,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userGetByID = `-- name: UserGetByID :one
SELECT id, email, full_name, avatar_url, status, deleted_at, created_at, updated_at FROM users 
WHERE 
    id = $1 AND 
    deleted_at IS NULL
`

func (q *Queries) UserGetByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, userGetByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.AvatarUrl,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userGetValidByIDForUpdate = `-- name: UserGetValidByIDForUpdate :one
SELECT id, email, full_name, avatar_url, status, deleted_at, created_at, updated_at FROM users 
WHERE 
    id = $1 AND 
    status = 1 AND -- mean: user status is active
    deleted_at IS NULL
FOR UPDATE
`

func (q *Queries) UserGetValidByIDForUpdate(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, userGetValidByIDForUpdate, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.AvatarUrl,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userPasswordResetCreate = `-- name: UserPasswordResetCreate :exec

INSERT INTO user_password_resets (user_id, token, expires_at)
VALUES ($1, $2, $3)
`

type UserPasswordResetCreateParams struct {
	UserID    int64
	Token     string
	ExpiresAt pgtype.Timestamptz
}

// ----- ----- ----- ----- -----
// user_password_resets table
// ----- ----- ----- ----- -----
func (q *Queries) UserPasswordResetCreate(ctx context.Context, arg UserPasswordResetCreateParams) error {
	_, err := q.db.Exec(ctx, userPasswordResetCreate, arg.UserID, arg.Token, arg.ExpiresAt)
	return err
}

const userPasswordResetGetValidForUpdate = `-- name: UserPasswordResetGetValidForUpdate :one
SELECT id, user_id, token, expires_at, used_at, created_at
FROM user_password_resets 
WHERE
    token = $1 AND
    used_at IS NULL AND
    expires_at > $2
FOR UPDATE
`

type UserPasswordResetGetValidForUpdateParams struct {
	Token string
	Now   pgtype.Timestamptz
}

func (q *Queries) UserPasswordResetGetValidForUpdate(ctx context.Context, arg UserPasswordResetGetValidForUpdateParams) (UserPasswordReset, error) {
	row := q.db.QueryRow(ctx, userPasswordResetGetValidForUpdate, arg.Token, arg.Now)
	var i UserPasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const userPasswordResetMarkUsed = `-- name: UserPasswordResetMarkUsed :exec
UPDATE user_password_resets
SET used_at = $1
WHERE
    id = $2 AND
    used_at IS NULL
`

type UserPasswordResetMarkUsedParams struct {
	UsedAt pgtype.Timestamptz
	ID     int64
}

func (q *Queries) UserPasswordResetMarkUsed(ctx context.Context, arg UserPasswordResetMarkUsedParams) error {
	_, err := q.db.Exec(ctx, userPasswordResetMarkUsed, arg.UsedAt, arg.ID)
	return err
}
