// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_auth.sql

package pkgsql

import (
	"context"
)

const mfaFactorGetByUserID = `-- name: MfaFactorGetByUserID :many

SELECT id, user_id, type, friendly_name, encrypted_secret, encryption_key_version, is_verified, created_at, updated_at FROM mfa_factors WHERE user_id = $1
`

// ----- ----- ----- ----- -----
//
// ----- ----- ----- ----- -----
func (q *Queries) MfaFactorGetByUserID(ctx context.Context, userID int64) ([]MfaFactor, error) {
	rows, err := q.db.Query(ctx, mfaFactorGetByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MfaFactor
	for rows.Next() {
		var i MfaFactor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.FriendlyName,
			&i.EncryptedSecret,
			&i.EncryptionKeyVersion,
			&i.IsVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userCredentialGetByUserID = `-- name: UserCredentialGetByUserID :one

SELECT user_id, hashed_password, password_last_changed_at FROM user_credentials WHERE user_id = $1
`

// ----- ----- ----- ----- -----
//
// ----- ----- ----- ----- -----
func (q *Queries) UserCredentialGetByUserID(ctx context.Context, userID int64) (UserCredential, error) {
	row := q.db.QueryRow(ctx, userCredentialGetByUserID, userID)
	var i UserCredential
	err := row.Scan(&i.UserID, &i.HashedPassword, &i.PasswordLastChangedAt)
	return i, err
}

const userGetByEmail = `-- name: UserGetByEmail :one
SELECT id, email, full_name, avatar_url, status, deleted_at, created_at, updated_at FROM users WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) UserGetByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, userGetByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.AvatarUrl,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
