// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForCreateIdentityMFABackupCodes implements pgx.CopyFromSource.
type iteratorForCreateIdentityMFABackupCodes struct {
	rows                 []CreateIdentityMFABackupCodesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateIdentityMFABackupCodes) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateIdentityMFABackupCodes) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].UserID,
		r.rows[0].Code,
	}, nil
}

func (r iteratorForCreateIdentityMFABackupCodes) Err() error {
	return nil
}

func (q *Queries) CreateIdentityMFABackupCodes(ctx context.Context, arg []CreateIdentityMFABackupCodesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"identity_mfa_backup_codes"}, []string{"id", "user_id", "code"}, &iteratorForCreateIdentityMFABackupCodes{rows: arg})
}
