// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
	auth_entity "github.com/shandysiswandi/gobite/internal/auth/entity"
	notif_entity "github.com/shandysiswandi/gobite/internal/notification/entity"
	vo "github.com/shandysiswandi/gobite/internal/pkg/valueobject"
)

type AuthChallenge struct {
	ID        int64
	Token     string
	UserID    int64
	Purpose   auth_entity.ChallengePurpose
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	Metadata  vo.JSONMap
	CreatedAt pgtype.Timestamptz
}

type AuthMfaBackupCode struct {
	ID        int64
	UserID    int64
	Code      string
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type AuthMfaFactor struct {
	ID           int64
	UserID       int64
	Type         auth_entity.MFAType
	FriendlyName string
	Secret       []byte
	KeyVersion   int16
	IsVerified   bool
	LastUsedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type AuthPermission struct {
	ID          int64
	Action      string
	Resource    string
	Description string
}

type AuthRefreshToken struct {
	ID                int64
	UserID            int64
	Token             string
	ExpiresAt         pgtype.Timestamptz
	Revoked           bool
	ReplacedByTokenID pgtype.Int8
	Metadata          vo.JSONMap
	CreatedAt         pgtype.Timestamptz
}

type AuthRole struct {
	ID          int64
	Name        string
	Description string
}

type AuthRolePermission struct {
	RoleID       int64
	PermissionID int64
}

type AuthUser struct {
	ID        int64
	Email     string
	FullName  string
	AvatarUrl string
	Status    auth_entity.UserStatus
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type AuthUserConnection struct {
	ID             int64
	UserID         int64
	Provider       string
	ProviderUserID string
	CreatedAt      pgtype.Timestamptz
}

type AuthUserCredential struct {
	UserID    int64
	Password  string
	UpdatedAt pgtype.Timestamptz
}

type AuthUserRole struct {
	UserID int64
	RoleID int64
}

type Notification struct {
	ID         int64
	UserID     int64
	CategoryID int64
	TriggerKey string
	Data       vo.JSONMap
	Metadata   vo.JSONMap
	ReadAt     pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type NotificationCategory struct {
	ID          int64
	Name        string
	Description string
	IsMandatory bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type NotificationDeliveryLog struct {
	ID               int64
	NotificationID   int64
	Channel          notif_entity.Channel
	Status           notif_entity.DeliveryStatus
	AttemptCount     int32
	NextRetryAt      pgtype.Timestamptz
	ProviderResponse vo.JSONMap
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type NotificationTemplate struct {
	ID         int64
	TriggerKey string
	CategoryID int64
	Channel    notif_entity.Channel
	Subject    string
	Body       string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type NotificationUserDevice struct {
	ID           int64
	UserID       int64
	DeviceToken  string
	Platform     string
	LastActiveAt pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type NotificationUserSetting struct {
	UserID     int64
	CategoryID int64
	Channel    notif_entity.Channel
	IsEnabled  bool
	UpdatedAt  pgtype.Timestamptz
}
