// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
	identity_entity "github.com/shandysiswandi/gobite/internal/identity/entity"
	notif_entity "github.com/shandysiswandi/gobite/internal/notification/entity"
	vo "github.com/shandysiswandi/gobite/internal/pkg/valueobject"
)

type IdentityCasbinRule struct {
	ID    int64
	Ptype string
	V0    pgtype.Text
	V1    pgtype.Text
	V2    pgtype.Text
	V3    pgtype.Text
	V4    pgtype.Text
	V5    pgtype.Text
}

type IdentityChallenge struct {
	ID        int64
	Token     string
	UserID    int64
	Purpose   identity_entity.ChallengePurpose
	ExpiresAt pgtype.Timestamptz
	Metadata  vo.JSONMap
	CreatedAt pgtype.Timestamptz
}

type IdentityMfaBackupCode struct {
	ID        int64
	UserID    int64
	Code      string
	UsedAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type IdentityMfaFactor struct {
	ID           int64
	UserID       int64
	Type         identity_entity.MFAType
	FriendlyName string
	Secret       []byte
	KeyVersion   int16
	IsVerified   bool
	LastUsedAt   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type IdentityRefreshToken struct {
	ID                int64
	UserID            int64
	Token             string
	ExpiresAt         pgtype.Timestamptz
	Revoked           bool
	ReplacedByTokenID pgtype.Int8
	Metadata          vo.JSONMap
	CreatedAt         pgtype.Timestamptz
}

type IdentityUser struct {
	ID        int64
	Email     string
	FullName  string
	AvatarUrl string
	Status    identity_entity.UserStatus
	DeletedAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	CreatedBy int64
	UpdatedBy int64
	DeletedBy pgtype.Int8
}

type IdentityUserConnection struct {
	ID             int64
	UserID         int64
	Provider       string
	ProviderUserID string
	CreatedAt      pgtype.Timestamptz
}

type IdentityUserCredential struct {
	UserID    int64
	Password  string
	UpdatedAt pgtype.Timestamptz
}

type Notification struct {
	ID         int64
	UserID     int64
	CategoryID int64
	TriggerKey string
	Data       vo.JSONMap
	Metadata   vo.JSONMap
	ReadAt     pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type NotificationCategory struct {
	ID          int64
	Name        string
	Description string
	IsMandatory bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type NotificationDeliveryLog struct {
	ID               int64
	NotificationID   int64
	Channel          notif_entity.Channel
	Status           notif_entity.DeliveryStatus
	AttemptCount     int32
	NextRetryAt      pgtype.Timestamptz
	ProviderResponse vo.JSONMap
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type NotificationTemplate struct {
	ID         int64
	TriggerKey string
	CategoryID int64
	Channel    notif_entity.Channel
	Subject    string
	Body       string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type NotificationUserDevice struct {
	ID           int64
	UserID       int64
	DeviceToken  string
	Platform     string
	LastActiveAt pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type NotificationUserSetting struct {
	UserID     int64
	CategoryID int64
	Channel    notif_entity.Channel
	IsEnabled  bool
	UpdatedAt  pgtype.Timestamptz
}
