// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	auth_entity "github.com/shandysiswandi/gobite/internal/auth/entity"
	vo "github.com/shandysiswandi/gobite/internal/pkg/valueobject"
)

const createAuthChallenge = `-- name: CreateAuthChallenge :exec
INSERT INTO auth_challenges (id, user_id, token, purpose, expires_at, metadata) 
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateAuthChallengeParams struct {
	ID        int64
	UserID    int64
	Token     string
	Purpose   auth_entity.ChallengePurpose
	ExpiresAt pgtype.Timestamptz
	Metadata  vo.JSONMap
}

func (q *Queries) CreateAuthChallenge(ctx context.Context, arg CreateAuthChallengeParams) error {
	_, err := q.db.Exec(ctx, createAuthChallenge,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.Purpose,
		arg.ExpiresAt,
		arg.Metadata,
	)
	return err
}

const createAuthMFAFactor = `-- name: CreateAuthMFAFactor :exec
INSERT INTO auth_mfa_factors (id, user_id, type, friendly_name, secret, key_version, is_verified)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateAuthMFAFactorParams struct {
	ID           int64
	UserID       int64
	Type         auth_entity.MFAType
	FriendlyName string
	Secret       []byte
	KeyVersion   int16
	IsVerified   bool
}

func (q *Queries) CreateAuthMFAFactor(ctx context.Context, arg CreateAuthMFAFactorParams) error {
	_, err := q.db.Exec(ctx, createAuthMFAFactor,
		arg.ID,
		arg.UserID,
		arg.Type,
		arg.FriendlyName,
		arg.Secret,
		arg.KeyVersion,
		arg.IsVerified,
	)
	return err
}

const createAuthRefreshToken = `-- name: CreateAuthRefreshToken :exec

INSERT INTO auth_refresh_tokens (id, user_id, token, expires_at, metadata) 
VALUES ($1, $2, $3, $4, $5)
`

type CreateAuthRefreshTokenParams struct {
	ID        int64
	UserID    int64
	Token     string
	ExpiresAt pgtype.Timestamptz
	Metadata  vo.JSONMap
}

// ***** ***** *****
// CREATE DATA
// ***** ***** *****
func (q *Queries) CreateAuthRefreshToken(ctx context.Context, arg CreateAuthRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createAuthRefreshToken,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.ExpiresAt,
		arg.Metadata,
	)
	return err
}

const createAuthUser = `-- name: CreateAuthUser :exec
INSERT INTO auth_users (id, email, full_name, avatar_url, status)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAuthUserParams struct {
	ID        int64
	Email     string
	FullName  string
	AvatarUrl string
	Status    auth_entity.UserStatus
}

func (q *Queries) CreateAuthUser(ctx context.Context, arg CreateAuthUserParams) error {
	_, err := q.db.Exec(ctx, createAuthUser,
		arg.ID,
		arg.Email,
		arg.FullName,
		arg.AvatarUrl,
		arg.Status,
	)
	return err
}

const createAuthUserCredential = `-- name: CreateAuthUserCredential :exec
INSERT INTO auth_user_credentials (user_id, password)
VALUES ($1, $2)
`

type CreateAuthUserCredentialParams struct {
	UserID   int64
	Password string
}

func (q *Queries) CreateAuthUserCredential(ctx context.Context, arg CreateAuthUserCredentialParams) error {
	_, err := q.db.Exec(ctx, createAuthUserCredential, arg.UserID, arg.Password)
	return err
}

const deleteAuthChallengeByID = `-- name: DeleteAuthChallengeByID :exec

DELETE FROM auth_challenges WHERE id = $1
`

// ***** ***** *****
// DELETE DATA
// ***** ***** *****
func (q *Queries) DeleteAuthChallengeByID(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAuthChallengeByID, id)
	return err
}

const getAuthChallengeUserByTokenPurpose = `-- name: GetAuthChallengeUserByTokenPurpose :one
SELECT u.id AS user_id, u.status, u.email, c.id, c.token, c.purpose, c.metadata
FROM auth_challenges c
JOIN auth_users AS u ON u.id = c.user_id
WHERE 
    c.token = $1 
    AND c.purpose = $2 
    AND c.expires_at > NOW()
`

type GetAuthChallengeUserByTokenPurposeParams struct {
	Token   string
	Purpose auth_entity.ChallengePurpose
}

type GetAuthChallengeUserByTokenPurposeRow struct {
	UserID   int64
	Status   auth_entity.UserStatus
	Email    string
	ID       int64
	Token    string
	Purpose  auth_entity.ChallengePurpose
	Metadata vo.JSONMap
}

func (q *Queries) GetAuthChallengeUserByTokenPurpose(ctx context.Context, arg GetAuthChallengeUserByTokenPurposeParams) (GetAuthChallengeUserByTokenPurposeRow, error) {
	row := q.db.QueryRow(ctx, getAuthChallengeUserByTokenPurpose, arg.Token, arg.Purpose)
	var i GetAuthChallengeUserByTokenPurposeRow
	err := row.Scan(
		&i.UserID,
		&i.Status,
		&i.Email,
		&i.ID,
		&i.Token,
		&i.Purpose,
		&i.Metadata,
	)
	return i, err
}

const getAuthMFAFactorByUserID = `-- name: GetAuthMFAFactorByUserID :many
SELECT id, user_id, type, friendly_name, secret, key_version, is_verified, last_used_at, created_at, updated_at FROM auth_mfa_factors 
WHERE 
    user_id = $1 AND 
    is_verified = $2
ORDER BY created_at ASC
`

type GetAuthMFAFactorByUserIDParams struct {
	UserID     int64
	IsVerified bool
}

func (q *Queries) GetAuthMFAFactorByUserID(ctx context.Context, arg GetAuthMFAFactorByUserIDParams) ([]AuthMfaFactor, error) {
	rows, err := q.db.Query(ctx, getAuthMFAFactorByUserID, arg.UserID, arg.IsVerified)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthMfaFactor
	for rows.Next() {
		var i AuthMfaFactor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.FriendlyName,
			&i.Secret,
			&i.KeyVersion,
			&i.IsVerified,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuthUserByEmail = `-- name: GetAuthUserByEmail :one
SELECT id, email, full_name, avatar_url, status, deleted_at, created_at, updated_at 
FROM auth_users 
WHERE 
    lower(email) = lower($1)
    AND deleted_at IS NULL
`

func (q *Queries) GetAuthUserByEmail(ctx context.Context, email string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getAuthUserByEmail, email)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.AvatarUrl,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthUserByEmailIncludeDeleted = `-- name: GetAuthUserByEmailIncludeDeleted :one
SELECT id, email, full_name, avatar_url, status, deleted_at, created_at, updated_at 
FROM auth_users
WHERE 
    lower(email) = lower($1)
`

func (q *Queries) GetAuthUserByEmailIncludeDeleted(ctx context.Context, email string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, getAuthUserByEmailIncludeDeleted, email)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.AvatarUrl,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuthUserCredentialInfo = `-- name: GetAuthUserCredentialInfo :one
SELECT u.id, u.email, u.status, c.password
FROM auth_users AS u
JOIN auth_user_credentials AS c ON u.id = c.user_id
WHERE
    u.id = $1
    AND u.deleted_at IS NULL
`

type GetAuthUserCredentialInfoRow struct {
	ID       int64
	Email    string
	Status   auth_entity.UserStatus
	Password string
}

func (q *Queries) GetAuthUserCredentialInfo(ctx context.Context, id int64) (GetAuthUserCredentialInfoRow, error) {
	row := q.db.QueryRow(ctx, getAuthUserCredentialInfo, id)
	var i GetAuthUserCredentialInfoRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Status,
		&i.Password,
	)
	return i, err
}

const getAuthUserLoginInfo = `-- name: GetAuthUserLoginInfo :one

SELECT u.id, u.email, u.status, c.password, EXISTS (SELECT 1 FROM auth_mfa_factors m WHERE m.user_id = u.id AND m.is_verified = TRUE) AS has_mfa
FROM auth_users AS u
JOIN auth_user_credentials AS c ON u.id = c.user_id
WHERE 
    lower(u.email) = lower($1) 
    AND u.deleted_at IS NULL
`

type GetAuthUserLoginInfoRow struct {
	ID       int64
	Email    string
	Status   auth_entity.UserStatus
	Password string
	HasMfa   bool
}

// ***** ***** *****
// SELECT DATA
// ***** ***** *****
func (q *Queries) GetAuthUserLoginInfo(ctx context.Context, email string) (GetAuthUserLoginInfoRow, error) {
	row := q.db.QueryRow(ctx, getAuthUserLoginInfo, email)
	var i GetAuthUserLoginInfoRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Status,
		&i.Password,
		&i.HasMfa,
	)
	return i, err
}

const getAuthUserRefreshToken = `-- name: GetAuthUserRefreshToken :one
SELECT rt.id, rt.user_id, rt.token, rt.expires_at, rt.revoked, rt.replaced_by_token_id, u.email, u.status AS user_status
FROM auth_refresh_tokens rt
JOIN auth_users u ON u.id = rt.user_id
WHERE 
    rt.token = $1
    AND u.deleted_at IS NULL
`

type GetAuthUserRefreshTokenRow struct {
	ID                int64
	UserID            int64
	Token             string
	ExpiresAt         pgtype.Timestamptz
	Revoked           bool
	ReplacedByTokenID pgtype.Int8
	Email             string
	UserStatus        auth_entity.UserStatus
}

func (q *Queries) GetAuthUserRefreshToken(ctx context.Context, token string) (GetAuthUserRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, getAuthUserRefreshToken, token)
	var i GetAuthUserRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.Revoked,
		&i.ReplacedByTokenID,
		&i.Email,
		&i.UserStatus,
	)
	return i, err
}

const markUsedAuthChallengeByID = `-- name: MarkUsedAuthChallengeByID :exec
UPDATE auth_challenges 
SET
    used_at = $1
WHERE 
    id = $2
`

type MarkUsedAuthChallengeByIDParams struct {
	UsedAt pgtype.Timestamptz
	ID     int64
}

func (q *Queries) MarkUsedAuthChallengeByID(ctx context.Context, arg MarkUsedAuthChallengeByIDParams) error {
	_, err := q.db.Exec(ctx, markUsedAuthChallengeByID, arg.UsedAt, arg.ID)
	return err
}

const replaceAuthRefreshToken = `-- name: ReplaceAuthRefreshToken :exec
UPDATE auth_refresh_tokens 
SET 
    revoked = TRUE, 
    replaced_by_token_id = $1::BIGINT
WHERE 
    id = $2
`

type ReplaceAuthRefreshTokenParams struct {
	NewTokenID int64
	OldTokenID int64
}

func (q *Queries) ReplaceAuthRefreshToken(ctx context.Context, arg ReplaceAuthRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, replaceAuthRefreshToken, arg.NewTokenID, arg.OldTokenID)
	return err
}

const revokeAllAuthRefreshToken = `-- name: RevokeAllAuthRefreshToken :exec
UPDATE auth_refresh_tokens 
SET 
    revoked = TRUE
WHERE 
    user_id = $1
`

func (q *Queries) RevokeAllAuthRefreshToken(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeAllAuthRefreshToken, userID)
	return err
}

const revokeAuthRefreshToken = `-- name: RevokeAuthRefreshToken :exec

UPDATE auth_refresh_tokens 
SET 
    revoked = TRUE
WHERE 
    token = $1
`

// ***** ***** *****
// UPDATE DATA
// ***** ***** *****
func (q *Queries) RevokeAuthRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, revokeAuthRefreshToken, token)
	return err
}

const updateAuthUserCredential = `-- name: UpdateAuthUserCredential :exec
UPDATE auth_user_credentials 
SET 
    password = $1
WHERE 
    user_id = $2
`

type UpdateAuthUserCredentialParams struct {
	Password string
	UserID   int64
}

func (q *Queries) UpdateAuthUserCredential(ctx context.Context, arg UpdateAuthUserCredentialParams) error {
	_, err := q.db.Exec(ctx, updateAuthUserCredential, arg.Password, arg.UserID)
	return err
}

const updateAuthUserName = `-- name: UpdateAuthUserName :exec
UPDATE auth_users
SET full_name = $1
WHERE
    id = $2 AND
    deleted_at IS NULL
`

type UpdateAuthUserNameParams struct {
	FullName string
	ID       int64
}

func (q *Queries) UpdateAuthUserName(ctx context.Context, arg UpdateAuthUserNameParams) error {
	_, err := q.db.Exec(ctx, updateAuthUserName, arg.FullName, arg.ID)
	return err
}
