// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query_notification.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	notif_entity "github.com/shandysiswandi/gobite/internal/notification/entity"
	vo "github.com/shandysiswandi/gobite/internal/pkg/valueobject"
)

const notificationCountUnread = `-- name: NotificationCountUnread :one
SELECT COUNT(*) 
FROM notifications 
WHERE 
    user_id = $1 AND 
    read_at IS NULL AND 
    deleted_at IS NULL
`

func (q *Queries) NotificationCountUnread(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, notificationCountUnread, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const notificationCreate = `-- name: NotificationCreate :exec
INSERT INTO notifications (id, user_id, category_id, trigger_key, data, metadata) 
VALUES ($1, $2, $3, $4, $5, $6)
`

type NotificationCreateParams struct {
	ID         int64
	UserID     int64
	CategoryID int64
	TriggerKey string
	Data       vo.JSONMap
	Metadata   vo.JSONMap
}

func (q *Queries) NotificationCreate(ctx context.Context, arg NotificationCreateParams) error {
	_, err := q.db.Exec(ctx, notificationCreate,
		arg.ID,
		arg.UserID,
		arg.CategoryID,
		arg.TriggerKey,
		arg.Data,
		arg.Metadata,
	)
	return err
}

const notificationDeliveryLogCreate = `-- name: NotificationDeliveryLogCreate :one
INSERT INTO notification_delivery_logs (notification_id, channel, status)
VALUES ($1, $2, $3) RETURNING id
`

type NotificationDeliveryLogCreateParams struct {
	NotificationID int64
	Channel        notif_entity.Channel
	Status         notif_entity.DeliveryStatus
}

func (q *Queries) NotificationDeliveryLogCreate(ctx context.Context, arg NotificationDeliveryLogCreateParams) (int64, error) {
	row := q.db.QueryRow(ctx, notificationDeliveryLogCreate, arg.NotificationID, arg.Channel, arg.Status)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const notificationDeliveryLogGetPendings = `-- name: NotificationDeliveryLogGetPendings :many
SELECT id, notification_id, channel, status, attempt_count, next_retry_at, provider_response, created_at, updated_at FROM notification_delivery_logs
WHERE 
    (status = $2::SMALLINT) OR 
    (status = $3::SMALLINT AND attempt_count < $4::int AND next_retry_at <= NOW())
ORDER BY created_at ASC
LIMIT $1
`

type NotificationDeliveryLogGetPendingsParams struct {
	Limit           int32
	StatusDefault   int16
	StatusFailed    int16
	MaxAttemptCount int32
}

// Fetches batch of logs to process.
// Criteria: Status is Queued (0) OR (Failed (3) AND time to retry has passed)
// Limit is essential for worker batching.
func (q *Queries) NotificationDeliveryLogGetPendings(ctx context.Context, arg NotificationDeliveryLogGetPendingsParams) ([]NotificationDeliveryLog, error) {
	rows, err := q.db.Query(ctx, notificationDeliveryLogGetPendings,
		arg.Limit,
		arg.StatusDefault,
		arg.StatusFailed,
		arg.MaxAttemptCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationDeliveryLog
	for rows.Next() {
		var i NotificationDeliveryLog
		if err := rows.Scan(
			&i.ID,
			&i.NotificationID,
			&i.Channel,
			&i.Status,
			&i.AttemptCount,
			&i.NextRetryAt,
			&i.ProviderResponse,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notificationDeliveryLogUpdateStatus = `-- name: NotificationDeliveryLogUpdateStatus :exec
UPDATE notification_delivery_logs
SET
    status = $1,
    provider_response = $2,
    updated_at = NOW(),
    attempt_count = attempt_count + 1,
    next_retry_at = $3
WHERE id = $4
`

type NotificationDeliveryLogUpdateStatusParams struct {
	Status           notif_entity.DeliveryStatus
	ProviderResponse vo.JSONMap
	NextRetryAt      pgtype.Timestamptz
	ID               int64
}

func (q *Queries) NotificationDeliveryLogUpdateStatus(ctx context.Context, arg NotificationDeliveryLogUpdateStatusParams) error {
	_, err := q.db.Exec(ctx, notificationDeliveryLogUpdateStatus,
		arg.Status,
		arg.ProviderResponse,
		arg.NextRetryAt,
		arg.ID,
	)
	return err
}

const notificationGetUserNotificationPaginate = `-- name: NotificationGetUserNotificationPaginate :many
SELECT 
    n.id, 
    n.trigger_key, 
    n.data, 
    n.metadata, 
    n.read_at, 
    n.created_at,
    nc.name as category_name,
    nc.description as category_description
FROM notifications n
JOIN notification_categories nc ON n.category_id = nc.id
WHERE 
    n.user_id = $3 AND 
    n.deleted_at IS NULL
ORDER BY n.created_at DESC
LIMIT $1 OFFSET $2
`

type NotificationGetUserNotificationPaginateParams struct {
	Limit  int32
	Offset int32
	UserID int64
}

type NotificationGetUserNotificationPaginateRow struct {
	ID                  int64
	TriggerKey          string
	Data                vo.JSONMap
	Metadata            vo.JSONMap
	ReadAt              pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	CategoryName        string
	CategoryDescription string
}

// Fetches a paginated list of notifications for a user.
// Joins with categories to get the display name (e.g., "Security", "Social").
func (q *Queries) NotificationGetUserNotificationPaginate(ctx context.Context, arg NotificationGetUserNotificationPaginateParams) ([]NotificationGetUserNotificationPaginateRow, error) {
	rows, err := q.db.Query(ctx, notificationGetUserNotificationPaginate, arg.Limit, arg.Offset, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationGetUserNotificationPaginateRow
	for rows.Next() {
		var i NotificationGetUserNotificationPaginateRow
		if err := rows.Scan(
			&i.ID,
			&i.TriggerKey,
			&i.Data,
			&i.Metadata,
			&i.ReadAt,
			&i.CreatedAt,
			&i.CategoryName,
			&i.CategoryDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notificationMarkRead = `-- name: NotificationMarkRead :exec
UPDATE notifications 
SET read_at = NOW() 
WHERE 
    id = $1 AND 
    user_id = $2 AND
    read_at IS NULL
`

type NotificationMarkReadParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) NotificationMarkRead(ctx context.Context, arg NotificationMarkReadParams) error {
	_, err := q.db.Exec(ctx, notificationMarkRead, arg.ID, arg.UserID)
	return err
}

const notificationSoftDelete = `-- name: NotificationSoftDelete :exec
UPDATE notifications 
SET deleted_at = NOW() 
WHERE id = $1 AND user_id = $2
`

type NotificationSoftDeleteParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) NotificationSoftDelete(ctx context.Context, arg NotificationSoftDeleteParams) error {
	_, err := q.db.Exec(ctx, notificationSoftDelete, arg.ID, arg.UserID)
	return err
}

const notificationTemplateGetByTrigger = `-- name: NotificationTemplateGetByTrigger :one
SELECT id, trigger_key, category_id, channel, subject, body, created_at, updated_at FROM notification_templates
WHERE 
    trigger_key = $1 AND
    channel = $2
`

type NotificationTemplateGetByTriggerParams struct {
	TriggerKey string
	Channel    notif_entity.Channel
}

func (q *Queries) NotificationTemplateGetByTrigger(ctx context.Context, arg NotificationTemplateGetByTriggerParams) (NotificationTemplate, error) {
	row := q.db.QueryRow(ctx, notificationTemplateGetByTrigger, arg.TriggerKey, arg.Channel)
	var i NotificationTemplate
	err := row.Scan(
		&i.ID,
		&i.TriggerKey,
		&i.CategoryID,
		&i.Channel,
		&i.Subject,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const notificationUserDeviceGetByUser = `-- name: NotificationUserDeviceGetByUser :many
SELECT device_token, platform 
FROM notification_user_devices 
WHERE user_id = $1
`

type NotificationUserDeviceGetByUserRow struct {
	DeviceToken string
	Platform    string
}

// Fetches all active devices for a user to broadcast push notifications.
func (q *Queries) NotificationUserDeviceGetByUser(ctx context.Context, userID int64) ([]NotificationUserDeviceGetByUserRow, error) {
	rows, err := q.db.Query(ctx, notificationUserDeviceGetByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationUserDeviceGetByUserRow
	for rows.Next() {
		var i NotificationUserDeviceGetByUserRow
		if err := rows.Scan(&i.DeviceToken, &i.Platform); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notificationUserDeviceRegister = `-- name: NotificationUserDeviceRegister :exec
INSERT INTO notification_user_devices (user_id, device_token, platform, last_active_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (device_token) 
DO UPDATE SET 
    user_id = EXCLUDED.user_id,
    platform = EXCLUDED.platform,
    last_active_at = NOW()
`

type NotificationUserDeviceRegisterParams struct {
	UserID      int64
	DeviceToken string
	Platform    string
}

// Saves or updates a device token.
// If the token exists, we update the user_id (in case of account switch).
func (q *Queries) NotificationUserDeviceRegister(ctx context.Context, arg NotificationUserDeviceRegisterParams) error {
	_, err := q.db.Exec(ctx, notificationUserDeviceRegister, arg.UserID, arg.DeviceToken, arg.Platform)
	return err
}

const notificationUserDeviceRemove = `-- name: NotificationUserDeviceRemove :exec
DELETE FROM notification_user_devices 
WHERE device_token = $1
`

// Called when a user logs out or the provider tells us the token is invalid.
func (q *Queries) NotificationUserDeviceRemove(ctx context.Context, deviceToken string) error {
	_, err := q.db.Exec(ctx, notificationUserDeviceRemove, deviceToken)
	return err
}

const notificationsMarkAllRead = `-- name: NotificationsMarkAllRead :exec
UPDATE notifications 
SET read_at = NOW() 
WHERE 
    user_id = $1 AND
    read_at IS NULL
`

func (q *Queries) NotificationsMarkAllRead(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, notificationsMarkAllRead, userID)
	return err
}
